services:
  authService-api:
    image: authservice-api
    build:
      context: .
      dockerfile: AuthService.API/Dockerfile
      secrets:
        - nuget_token
    ports:
      - "9000:80"
      - "9001:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+80;https://+443
      - ConnectionStrings__DefaultConnection=Host=authService-db;Port=5432;Database=authService;Username=authService_user;Password=authService_password;Include Error Detail=true
      - ConnectionStrings__Redis=authService-redis:6379
      - Kafka__BootstrapServers=kafka:29092
      - InternalAuth__Issuer=http://auth.internal
    entrypoint:
      - "dotnet"
      - "AuthService.API.dll"
    volumes:
      - "users_data:/app/data"
      - "./AuthService.API/Keys:/app/Keys:ro"
    networks:
      - authService-network
      - microservices
    depends_on:
      authService-db:
        condition: service_healthy
      redis:
        condition: service_healthy
  authService-db:
    image: postgres:15
    container_name: authService-db
    environment:
      POSTGRES_DB: authService
      POSTGRES_USER: authService_user
      POSTGRES_PASSWORD: authService_password
    ports:
      - "9432:5432"
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - authService-network
  redis:
    image: redis:alpine
    container_name: authService-redis
    ports:
      - "9532:6379"
    volumes:
      - authService_redis_data:/var/lib/redis/data
    restart:
      unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 50s
      timeout: 2s
      retries: 5
    networks:
      - authService-network
volumes:
  users_data:
  auth_postgres_data:
  authService_redis_data:

networks:
  authService-network:
    driver: bridge
    external: true
  microservices:
    external: true  
    
secrets:
  nuget_token:
    file: ./secrets/nuget_token.txt